version: '3.8'
services:
  key-exchange-api:
    container_name: key-exchange-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    build:
      dockerfile: DockerfileDev
      context: ./
    ports:
      - "8080:80"
      - "5000:5000"
      - "443:443"
    volumes:
      - .:/src
    depends_on:
      - database

  database:
    container_name: database-dev
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
        - "5434:1433"
    env_file:
      - secret.env
        
  postgres-db:
    container_name: key-exchange-psql
    image: postgres:14.1
    ports:
      - "5432:5432"
    env_file:
      - secret.env
    environment:
      POSTGRES_PASSWORD: password
      