version: '3.8'
services:
  api:
    container_name: key-exchange-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    build:
      dockerfile: DockerfileDev
      context: KeyExchangeAPI\KeyExchangeAPI\
    ports:
      - "8080:80"
      - "5000:5000"
      - "443:443"
    volumes:
      - ../../src:/src
    depends_on:
      - database

  database:
    container_name: key-exchange-database
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password